[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.max_wasted_percentage=10
opcache.validate_timestamps=1
; Revalidate a cada 2 segundos (ideal para local com bind mount no Windows, economiza IOPS absurdamente)
opcache.revalidate_freq=2
opcache.fast_shutdown=1

[core]
; Reduz a necessidade do PHP checar estatísticas de arquivo no disco toda hora
realpath_cache_size=4096K
realpath_cache_ttl=600

memory_limit=512M
max_execution_time=60
post_max_size=100M
upload_max_filesize=100M
expose_php=Off
